# Generated by Django 5.0.6 on 2024-05-31 20:22

import django.core.serializers.json
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abstract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField()),
                (
                    "alternative_names",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("standardized_name", models.CharField(null=True)),
                ("first_names", models.CharField(null=True)),
                ("last_name", models.CharField(null=True)),
                ("middle_names", models.CharField(null=True)),
                ("initials", models.CharField(null=True)),
                ("prefixes", models.CharField(null=True)),
                ("suffixes", models.CharField(null=True)),
                ("orcid", models.URLField(max_length=20000, null=True)),
                ("scopus", models.CharField(null=True)),
                ("isni", models.CharField(null=True)),
                ("openalex_id", models.URLField(max_length=20000, null=True)),
                ("openalex_created_date", models.DateField(null=True)),
                ("openalex_updated_date", models.DateTimeField(null=True)),
                ("works_api_url", models.URLField(max_length=20000, null=True)),
                ("works_count", models.IntegerField(null=True)),
                ("cited_by_count", models.IntegerField(null=True)),
                (
                    "counts_by_year",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("impact_factor", models.FloatField(null=True)),
                ("h_index", models.IntegerField(null=True)),
                ("i10_index", models.IntegerField(null=True)),
                ("pure_uuid", models.UUIDField(default=None, null=True, unique=True)),
                ("pure_id", models.IntegerField(null=True)),
                ("pure_last_modified", models.DateTimeField(null=True)),
                (
                    "author_links",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("avatar_url", models.URLField(max_length=20000, null=True)),
                ("profile_url", models.URLField(max_length=20000, null=True)),
                ("research_url", models.URLField(max_length=20000, null=True)),
                ("email", models.CharField(null=True)),
                ("searched_name", models.CharField(null=True)),
                ("found_name", models.CharField(null=True)),
                ("match_similarity", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CrossrefData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataCiteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpenAireData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RepositoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("openalex_id", models.URLField(max_length=20000)),
                ("name", models.CharField()),
                (
                    "alternate_names",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("country_code", models.CharField(null=True)),
                (
                    "counts_by_year",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("openalex_created_date", models.DateField()),
                ("openalex_updated_date", models.DateTimeField()),
                ("grants_count", models.IntegerField()),
                ("description", models.CharField(null=True)),
                ("homepage_url", models.URLField(max_length=20000, null=True)),
                ("ror", models.URLField(max_length=20000, null=True)),
                ("wikidata", models.URLField(max_length=20000, null=True)),
                ("crossref", models.CharField(null=True)),
                ("doi", models.URLField(max_length=20000, null=True)),
                ("image_thumbnail_url", models.URLField(max_length=20000, null=True)),
                ("image_url", models.URLField(max_length=20000, null=True)),
                ("impact_factor", models.FloatField()),
                ("h_index", models.IntegerField()),
                ("i10_index", models.IntegerField()),
                ("works_count", models.IntegerField()),
                ("cited_by_count", models.IntegerField()),
                (
                    "as_other_funders",
                    models.ManyToManyField(
                        related_name="other_funders_entries", to="mus_wizard.funder"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("EEMCS", "Eemcs"),
                            ("BMS", "Bms"),
                            ("ET", "Et"),
                            ("ITC", "Itc"),
                            ("TNW", "Tnw"),
                            ("OTHER", "Other"),
                        ]
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="mus_wizard__name_ab46a1_idx"),
                    models.Index(
                        fields=["faculty"], name="mus_wizard__faculty_7cd57d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "years",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("position", models.CharField(blank=True, default="")),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation_details",
                        to="mus_wizard.author",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="affiliations", to="mus_wizard.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MongoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "source_collection",
                    models.CharField(
                        choices=[
                            ("works_openalex", "Works Openalex"),
                            ("authors_openalex", "Authors Openalex"),
                            ("topics_openalex", "Topics Openalex"),
                            ("sources_openalex", "Sources Openalex"),
                            ("funders_openalex", "Funders Openalex"),
                            ("publishers_openalex", "Publishers Openalex"),
                            ("institutions_openalex", "Institutions Openalex"),
                            ("authors_pure", "Authors Pure"),
                            ("employees_peoplepage", "Employees Peoplepage"),
                            ("deals_journalbrowser", "Deals Journalbrowser"),
                            ("items_crossref", "Items Crossref"),
                            ("items_datacite", "Items Datacite"),
                            ("items_openaire", "Items Openaire"),
                            ("items_orcid", "Items Orcid"),
                        ]
                    ),
                ),
                ("source_id", models.CharField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField()),
                (
                    "name_acronyms",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "name_alternatives",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("ror", models.CharField(null=True)),
                ("openalex_id", models.URLField(max_length=20000)),
                ("wikipedia", models.URLField(max_length=20000, null=True)),
                ("wikidata", models.URLField(max_length=20000, null=True)),
                ("openalex_created_date", models.DateField()),
                ("openalex_updated_date", models.DateTimeField()),
                ("country_code", models.CharField(null=True)),
                ("works_count", models.IntegerField(null=True)),
                ("cited_by_count", models.IntegerField(null=True)),
                ("impact_factor", models.FloatField(null=True)),
                ("h_index", models.IntegerField(null=True)),
                ("i10_index", models.IntegerField(null=True)),
                ("image_thumbnail_url", models.URLField(max_length=20000, null=True)),
                ("image_url", models.URLField(max_length=20000, null=True)),
                (
                    "lineage",
                    models.ManyToManyField(
                        related_name="org_children", to="mus_wizard.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Authorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("first", "First"),
                            ("middle", "Middle"),
                            ("last", "Last"),
                            ("-", "Unknown"),
                        ],
                        default="-",
                    ),
                ),
                ("is_corresponding", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="mus_wizard.author",
                    ),
                ),
                (
                    "affiliations",
                    models.ManyToManyField(
                        related_name="authorships", to="mus_wizard.organization"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="affiliations",
            field=models.ManyToManyField(
                related_name="authors",
                through="mus_wizard.Affiliation",
                to="mus_wizard.organization",
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliation_details",
                to="mus_wizard.organization",
            ),
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("openalex_id", models.URLField(max_length=20000, null=True)),
                ("openalex_created_date", models.DateField(null=True)),
                ("openalex_updated_date", models.DateTimeField(null=True)),
                ("name", models.CharField()),
                (
                    "alternate_names",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("country_code", models.CharField(null=True)),
                (
                    "counts_by_year",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("hierarchy_level", models.IntegerField()),
                ("ror", models.CharField(null=True)),
                ("wikidata", models.URLField(max_length=20000, null=True)),
                ("image_url", models.URLField(max_length=20000, null=True)),
                ("image_thumbnail_url", models.URLField(max_length=20000, null=True)),
                ("sources_api_url", models.URLField(max_length=20000, null=True)),
                ("impact_factor", models.FloatField(null=True)),
                ("h_index", models.IntegerField(null=True)),
                ("i10_index", models.IntegerField(null=True)),
                ("works_count", models.IntegerField()),
                (
                    "as_funder",
                    models.ManyToManyField(
                        related_name="as_publisher", to="mus_wizard.funder"
                    ),
                ),
                (
                    "as_institution",
                    models.ManyToManyField(
                        related_name="as_publisher", to="mus_wizard.organization"
                    ),
                ),
                (
                    "lineage",
                    models.ManyToManyField(
                        related_name="publ_children", to="mus_wizard.publisher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("openalex_id", models.URLField(max_length=20000)),
                ("openalex_created_date", models.DateField()),
                ("openalex_updated_date", models.DateTimeField()),
                ("is_in_doaj", models.BooleanField(default=False)),
                ("is_oa", models.BooleanField(default=False)),
                ("country_code", models.CharField(null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("J", "Journal"),
                            ("BS", "Book Series"),
                            ("R", "Repository"),
                            ("EP", "Ebook Platform"),
                            ("C", "Conference"),
                            ("M", "Metadata"),
                            ("U", "Unknown"),
                        ],
                        default="U",
                    ),
                ),
                ("title", models.CharField()),
                (
                    "alternate_titles",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("abbreviated_title", models.CharField(null=True)),
                ("homepage_url", models.URLField(max_length=20000, null=True)),
                ("host_org_name", models.CharField(null=True)),
                ("issn_l", models.CharField(null=True)),
                (
                    "issn",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("wikidata", models.URLField(max_length=20000, null=True)),
                ("fatcat", models.URLField(max_length=20000, null=True)),
                ("mag", models.CharField(null=True)),
                ("cited_by_count", models.IntegerField()),
                (
                    "counts_by_year",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("works_api_url", models.URLField(max_length=20000)),
                ("works_count", models.IntegerField()),
                ("impact_factor", models.FloatField()),
                ("h_index", models.IntegerField()),
                ("i10_index", models.IntegerField()),
                (
                    "apc_prices",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("apc_usd", models.IntegerField(null=True)),
                (
                    "lineage",
                    models.ManyToManyField(
                        related_name="children", to="mus_wizard.publisher"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="repositories",
            field=models.ManyToManyField(
                related_name="repositories", to="mus_wizard.source"
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("J", "Journal"),
                            ("BS", "Book Series"),
                            ("R", "Repository"),
                            ("EP", "Ebook Platform"),
                            ("C", "Conference"),
                            ("M", "Metadata"),
                            ("U", "Unknown"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("is_oa", models.BooleanField(default=False)),
                ("landing_page_url", models.URLField(max_length=20000, null=True)),
                ("pdf_url", models.URLField(max_length=20000, null=True)),
                ("license", models.CharField(null=True)),
                ("license_id", models.CharField(null=True)),
                ("version", models.CharField(null=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_best_oa", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="mus_wizard.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "dealtype",
                    models.CharField(
                        choices=[
                            ("FL", "100% APC discount for UT authors"),
                            ("20", "20% APC discount for UT authors"),
                            ("15", "15% APC discount for UT authors"),
                            ("10", "10% APC discount for UT authors"),
                            ("PR", "Probably no APC costs"),
                            ("NO", "No APC discount"),
                            ("UN", "APC costs unknown"),
                        ],
                        default="UN",
                    ),
                ),
                (
                    "issns",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("jb_url", models.URLField(max_length=20000)),
                (
                    "keywords",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("journal_title", models.CharField()),
                ("publisher_name", models.CharField(blank=True, default="")),
                ("openalex_id", models.URLField(max_length=20000, unique=True)),
                ("openalex_display_name", models.CharField(blank=True, default="")),
                (
                    "openalex_issn",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "openalex_issn_l",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("openalex_type", models.CharField(blank=True, default="")),
                (
                    "related_sources",
                    models.ManyToManyField(
                        db_index=True, related_name="deals", to="mus_wizard.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("PR", "Peer Reviewed"),
                            ("OR", "Only Repo"),
                            ("FR", "Found In Repository"),
                            ("RF", "Repo Found In Openalex"),
                            ("IA", "Institute Author Match"),
                            ("HE", "Has Error"),
                            ("GN", "Generic"),
                            ("OT", "Org Type"),
                        ],
                        default="GN",
                        max_length=2,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("description", models.CharField()),
                ("name", models.CharField()),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Physical Sciences", "Physical Sciences"),
                            ("Social Sciences", "Social Sciences"),
                            ("Health Sciences", "Health Sciences"),
                            ("Life Sciences", "Life Sciences"),
                        ]
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("Medicine", "Medicine"),
                            ("Social Sciences", "Social Sciences"),
                            ("Engineering", "Engineering"),
                            ("Arts and Humanities", "Arts And Humanities"),
                            ("Computer Science", "Computer Science"),
                            (
                                "Biochemistry, Genetics and Molecular Biology",
                                "Biochemistry Genetics And Molecular Biology",
                            ),
                            (
                                "Agricultural and Biological Sciences",
                                "Agricultural And Biological Sciences",
                            ),
                            ("Environmental Science", "Environmental Science"),
                            ("Physics and Astronomy", "Physics And Astronomy"),
                            (
                                "Business, Management and Accounting",
                                "Business Management And Accounting",
                            ),
                            ("Materials Science", "Materials Science"),
                            (
                                "Economics, Econometrics and Finance",
                                "Economics Econometrics And Finance",
                            ),
                            ("Health Professions", "Health Professions"),
                            ("Psychology", "Psychology"),
                            ("Chemistry", "Chemistry"),
                            (
                                "Earth and Planetary Sciences",
                                "Earth And Planetary Sciences",
                            ),
                            ("Neuroscience", "Neuroscience"),
                            ("Mathematics", "Mathematics"),
                            (
                                "Immunology and Microbiology",
                                "Immunology And Microbiology",
                            ),
                            ("Decision Sciences", "Decision Sciences"),
                            ("Energy", "Energy"),
                            ("Nursing", "Nursing"),
                            (
                                "Pharmacology, Toxicology and Pharmaceutics",
                                "Pharmacology Toxicology And Pharmaceuticals",
                            ),
                            ("Dentistry", "Dentistry"),
                            ("Chemical Engineering", "Chemical Engineering"),
                            ("Veterinary", "Veterinary"),
                        ]
                    ),
                ),
                ("openalex_id", models.URLField(max_length=20000, unique=True)),
                ("works_count", models.IntegerField()),
                (
                    "keywords",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("wikipedia", models.URLField(max_length=20000)),
                ("subfield", models.CharField()),
                ("subfield_id", models.IntegerField()),
                (
                    "siblings",
                    models.ManyToManyField(
                        related_name="set_siblings", to="mus_wizard.topic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_topics",
                        to="mus_wizard.source",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_topics",
                        to="mus_wizard.topic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="source",
            name="topics",
            field=models.ManyToManyField(
                related_name="sources",
                through="mus_wizard.SourceTopic",
                to="mus_wizard.topic",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_topics",
                        to="mus_wizard.organization",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_topics",
                        to="mus_wizard.topic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="topics",
            field=models.ManyToManyField(
                related_name="organizations",
                through="mus_wizard.OrganizationTopic",
                to="mus_wizard.topic",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="topics",
            field=models.ManyToManyField(related_name="authors", to="mus_wizard.topic"),
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("openalex_id", models.URLField(max_length=20000, null=True)),
                ("openalex_created_date", models.DateField(null=True)),
                ("openalex_updated_date", models.DateTimeField(null=True)),
                ("ngrams_url", models.URLField(max_length=20000, null=True)),
                ("cited_by_api_url", models.URLField(max_length=20000, null=True)),
                ("cited_by_count", models.IntegerField(null=True)),
                (
                    "cited_by_percentile_year",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("referenced_works_count", models.IntegerField(null=True)),
                ("doi", models.CharField(null=True)),
                ("title", models.CharField()),
                ("publication_year", models.IntegerField()),
                ("publication_date", models.DateField()),
                ("pmid", models.CharField(null=True)),
                ("pmcid", models.CharField(null=True)),
                ("isbn", models.CharField(null=True)),
                ("mag", models.CharField(null=True)),
                ("language", models.CharField(null=True)),
                (
                    "mesh_terms",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("type_crossref", models.CharField(null=True)),
                ("volume", models.CharField(null=True)),
                ("issue", models.CharField(null=True)),
                ("first_page", models.CharField(null=True)),
                ("last_page", models.CharField(null=True)),
                ("pages", models.CharField(null=True)),
                ("article_number", models.CharField(null=True)),
                ("locations_count", models.IntegerField(null=True)),
                ("is_oa", models.BooleanField(default=False)),
                (
                    "oa_status",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("bronze", "Bronze"),
                            ("green", "Green"),
                            ("hybrid", "Hybrid"),
                            ("closed", "Closed"),
                            ("not_set", "Not Set"),
                        ],
                        default="not_set",
                    ),
                ),
                ("oa_url", models.URLField(max_length=20000, null=True)),
                ("is_also_green", models.BooleanField(default=False)),
                (
                    "itemtype",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("conference_proceeding", "Conference Proceeding"),
                            ("journal_article", "Journal Article"),
                            ("dissertation", "Dissertation"),
                            ("report", "Report"),
                            ("other", "Other"),
                            ("not_set", "Not Set"),
                        ],
                        default="not_set",
                    ),
                ),
                (
                    "apc_listed",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "apc_paid",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("has_fulltext", models.BooleanField(default=False)),
                ("is_paratext", models.BooleanField(default=False)),
                ("is_retracted", models.BooleanField(default=False)),
                (
                    "indexed_in",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "sdgs",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "versions",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("found_in_institute_repo", models.BooleanField(default=False)),
                (
                    "repo_keywords",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("found_in_openaire", models.BooleanField(default=False)),
                ("found_in_datacite", models.BooleanField(default=False)),
                ("found_in_crossref", models.BooleanField(default=False)),
                (
                    "abstract",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mus_wizard.abstract",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="works",
                        through="mus_wizard.Authorship",
                        to="mus_wizard.author",
                    ),
                ),
                (
                    "crossref_data",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mus_wizard.crossrefdata",
                    ),
                ),
                (
                    "datacite_data",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mus_wizard.datacitedata",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="mus_wizard.source",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="works", to="mus_wizard.location"
                    ),
                ),
                (
                    "openaire_data",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mus_wizard.openairedata",
                    ),
                ),
                (
                    "primary_topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_works",
                        to="mus_wizard.topic",
                    ),
                ),
                (
                    "repo_data",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mus_wizard.repositorydata",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(related_name="works", to="mus_wizard.topic"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("award_id", models.CharField(null=True)),
                ("funder_name", models.CharField(null=True)),
                (
                    "funder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="mus_wizard.funder",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="mus_wizard.work",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authorship",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorships",
                to="mus_wizard.work",
            ),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_cfc476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(fields=["doi"], name="mus_wizard__doi_78fd89_idx"),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(fields=["ror"], name="mus_wizard__ror_9f6388_idx"),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(
                fields=["crossref"], name="mus_wizard__crossre_18e160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(
                fields=["country_code"], name="mus_wizard__country_bfa7ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(
                fields=["image_url"], name="mus_wizard__image_u_6bd674_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(
                fields=["image_thumbnail_url"], name="mus_wizard__image_t_09235e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(
                fields=["wikidata"], name="mus_wizard__wikidat_8f2379_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mongodata",
            index=models.Index(
                fields=["content_type", "object_id", "source_collection"],
                name="mus_wizard__content_26c637_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(
                fields=["author", "organization"], name="mus_wizard__author__cb60da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(
                fields=["organization", "author"], name="mus_wizard__organiz_8c8472_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(fields=["years"], name="mus_wizard__years_fd49ec_idx"),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_35115d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(fields=["ror"], name="mus_wizard__ror_254c4c_idx"),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["wikidata"], name="mus_wizard__wikidat_e4d9c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["image_url"], name="mus_wizard__image_u_3d0f01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["image_thumbnail_url"], name="mus_wizard__image_t_b9b03f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["source", "source_type"], name="mus_wizard__source__220b33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["landing_page_url"], name="mus_wizard__landing_b24d43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["pdf_url"], name="mus_wizard__pdf_url_15689d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["license"], name="mus_wizard__license_96da2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["license_id"], name="mus_wizard__license_253226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_best_oa"], name="mus_wizard__is_best_f98ebb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_accepted"], name="mus_wizard__is_acce_d90828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_published"], name="mus_wizard__is_publ_700770_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_primary"], name="mus_wizard__is_prim_84b0a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_a3110e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_display_name"], name="mus_wizard__openale_58254c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_issn"], name="mus_wizard__openale_dafcf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_issn_l"], name="mus_wizard__openale_2c83b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_type"], name="mus_wizard__openale_85b477_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["journal_title"], name="mus_wizard__journal_b0f005_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["publisher_name"], name="mus_wizard__publish_61ed51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(fields=["jb_url"], name="mus_wizard__jb_url_7530db_idx"),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(fields=["issns"], name="mus_wizard__issns_3396a4_idx"),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["dealtype"], name="mus_wizard__dealtyp_e7a100_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["content_type", "object_id", "tag_type"],
                name="mus_wizard__content_02602a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_0c8d6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["wikipedia"], name="mus_wizard__wikiped_69e183_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcetopic",
            index=models.Index(
                fields=["source", "topic"], name="mus_wizard__source__aa7170_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_4a1000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["issn_l"], name="mus_wizard__issn_l_d1da4b_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["issn"], name="mus_wizard__issn_52ee13_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["wikidata"], name="mus_wizard__wikidat_e3cd65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["source_type"], name="mus_wizard__source__bf51b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["homepage_url"], name="mus_wizard__homepag_2af9fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["is_in_doaj"], name="mus_wizard__is_in_d_853e93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["is_oa"], name="mus_wizard__is_oa_35b585_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["country_code"], name="mus_wizard__country_c6b778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationtopic",
            index=models.Index(
                fields=["organization", "topic"], name="mus_wizard__organiz_afbd7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_996529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["ror"], name="mus_wizard__ror_736e28_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["wikipedia"], name="mus_wizard__wikiped_2a9295_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["wikidata"], name="mus_wizard__wikidat_893db2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["country_code"], name="mus_wizard__country_6c8046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["image_url"], name="mus_wizard__image_u_72f56f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["image_thumbnail_url"], name="mus_wizard__image_t_db9131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_43fbee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["pure_uuid"], name="mus_wizard__pure_uu_750429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["pure_id"], name="mus_wizard__pure_id_85e9d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["orcid"], name="mus_wizard__orcid_c2fd18_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["scopus"], name="mus_wizard__scopus_719aed_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["isni"], name="mus_wizard__isni_281c23_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["email"], name="mus_wizard__email_d0d957_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["openalex_id"], name="mus_wizard__openale_c2b033_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["doi"], name="mus_wizard__doi_61af71_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["publication_date"], name="mus_wizard__publica_5353ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["publication_year"], name="mus_wizard__publica_b8264a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["oa_status"], name="mus_wizard__oa_stat_31f059_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["pmid"], name="mus_wizard__pmid_37ca70_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["pmcid"], name="mus_wizard__pmcid_3d2cb9_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["isbn"], name="mus_wizard__isbn_da0b34_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["mag"], name="mus_wizard__mag_cd56f0_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["is_also_green"], name="mus_wizard__is_also_af606b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["is_oa"], name="mus_wizard__is_oa_ea343c_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["itemtype"], name="mus_wizard__itemtyp_9c3dd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["type_crossref"], name="mus_wizard__type_cr_98dce3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["award_id"], name="mus_wizard__award_i_d57e08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["funder_name"], name="mus_wizard__funder__566623_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(fields=["work"], name="mus_wizard__work_id_d25528_idx"),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["funder"], name="mus_wizard__funder__9078e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authorship",
            index=models.Index(
                fields=["author", "work"], name="mus_wizard__author__0c5d2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authorship",
            index=models.Index(
                fields=["work", "author"], name="mus_wizard__work_id_1affc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authorship",
            index=models.Index(
                condition=models.Q(("is_corresponding", True)),
                fields=["is_corresponding"],
                name="cor_index",
            ),
        ),
    ]
