# Generated by Django 5.0.6 on 2024-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mus_wizard", "0003_group_mus_wizard__interna_19dcb1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="repositorydata",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="internal_repository_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="pure_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["internal_repository_id"], name="mus_wizard__interna_0fa6cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funder",
            index=models.Index(
                fields=["internal_repository_id"], name="mus_wizard__interna_4cf2f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["internal_repository_id"], name="mus_wizard__interna_506ef5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["internal_repository_id"], name="mus_wizard__interna_d04cb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["internal_repository_id"], name="mus_wizard__interna_a8dfec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["internal_repository_id"], name="mus_wizard__interna_916337_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["internal_repository_id"], name="mus_wizard__interna_d77625_idx"
            ),
        ),
    ]
