# Generated by Django 5.0.6 on 2024-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mus_wizard", "0005_alter_author_pure_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="publication_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="publication_year",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(null=True),
        ),
    ]
