# Generated by Django 5.0 on 2024-01-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="afasdata",
            name="jobs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
