# Generated by Django 5.0 on 2024-01-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0002_afasdata_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="afas_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authors",
                to="PureOpenAlex.afasdata",
            ),
        ),
    ]
