# Generated by Django 5.0 on 2024-01-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0003_alter_author_afas_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="openalex_url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["afas_data"], name="PureOpenAle_afas_da_3bf8c4_idx"
            ),
        ),
    ]
