# Generated by Django 5.0.2 on 2024-02-17 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0005_remove_author_pureopenale_faculty_eaa6ae_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="utdata",
            old_name="job_title",
            new_name="current_position",
        ),
    ]
