# Generated by Django 5.0.2 on 2024-02-17 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0007_utdata_current_faculty_utdata_current_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="subjects_crossref",
        ),
        migrations.RemoveField(
            model_name="pureentry",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="concepts",
        ),
        migrations.RemoveField(
            model_name="source",
            name="concepts",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="crossref_json",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="openalex_json",
        ),
        migrations.DeleteModel(
            name="APIResponse",
        ),
        migrations.DeleteModel(
            name="Concept",
        ),
    ]
