# Generated by Django 5.0.2 on 2024-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0008_remove_paper_subjects_crossref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utdata",
            name="employment_data",
            field=models.JSONField(null=True),
        ),
    ]
