# Generated by Django 5.0.2 on 2024-02-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0009_utdata_employment_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pureentry",
            name="doi",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="pureentry",
            name="isbn",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="pureentry",
            name="other_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pureentry",
            name="researchutwente",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="pureentry",
            name="risutwente",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="pureentry",
            name="scopus",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
