# Generated by Django 5.0.2 on 2024-02-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0011_auto_20240218_2349"),
    ]

    operations = [
        migrations.AddField(
            model_name="pureentry",
            name="duplicate_ids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
