# Generated by Django 5.0.2 on 2024-02-19 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0012_pureentry_duplicate_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pureentry",
            name="identifiers",
        ),
        migrations.DeleteModel(
            name="Identifier",
        ),
    ]
