# Generated by Django 5.0.2 on 2024-02-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0013_remove_pureentry_identifiers_delete_identifier"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["openalex_url"], name="PureOpenAle_openale_479667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utdata",
            index=models.Index(
                fields=["current_group"], name="PureOpenAle_current_5feba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utdata",
            index=models.Index(
                fields=["current_faculty"], name="PureOpenAle_current_4fb84e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utdata",
            index=models.Index(
                fields=["current_position"], name="PureOpenAle_current_082088_idx"
            ),
        ),
    ]
