# Generated by Django 5.0.2 on 2024-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0014_author_pureopenale_openale_479667_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(fields=["id"], name="PureOpenAle_id_4a0282_idx"),
        ),
    ]
