# Generated by Django 5.0.2 on 2024-02-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0016_alter_utdata_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utdata",
            name="employee",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PureOpenAlex.author",
            ),
        ),
    ]
