# Generated by Django 5.0.2 on 2024-02-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0017_alter_utdata_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="known_as",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="scopus_id",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="openalex_url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["openalex_url"], name="PureOpenAle_openale_85685f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["openalex_url"], name="PureOpenAle_openale_f89e2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["openalex_url"], name="PureOpenAle_openale_b59db0_idx"
            ),
        ),
    ]
