# Generated by Django 5.0.2 on 2024-02-22 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0018_author_known_as_author_scopus_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utdata",
            name="departments",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
