# Generated by Django 5.0.2 on 2024-02-22 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0019_remove_utdata_departments_delete_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="afas_data",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="PureOpenAlex.afasdata",
            ),
        ),
    ]
