# Generated by Django 5.0.2 on 2024-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0023_rename_doaj_journal_is_in_doaj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pureauthor",
            name="author",
        ),
        migrations.RemoveField(
            model_name="pureentry",
            name="contributors",
        ),
        migrations.RemoveField(
            model_name="pureentry",
            name="creators",
        ),
        migrations.AlterModelOptions(
            name="author",
            options={},
        ),
        migrations.AlterModelOptions(
            name="dealdata",
            options={},
        ),
        migrations.AlterModelOptions(
            name="paper",
            options={},
        ),
        migrations.AlterModelOptions(
            name="source",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="PureOpenAle_name_06513e_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="PureOpenAle_ror_223401_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="PureOpenAle_openale_85685f_idx",
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=[
                    "openalex_url",
                    "name",
                    "is_ut",
                    "scopus_id",
                    "orcid",
                    "known_as",
                ],
                name="PureOpenAle_openale_77b20d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authorship",
            index=models.Index(
                fields=["author", "paper"], name="PureOpenAle_author__5a6b97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["deal_status", "publisher", "oa_type", "jb_url"],
                name="PureOpenAle_deal_st_37e6da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["openalex_url", "name", "issn", "e_issn", "publisher"],
                name="PureOpenAle_openale_59c19a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["openalex_url", "name", "country_code", "ror", "type"],
                name="PureOpenAle_openale_6cfb9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=[
                    "openalex_url",
                    "doi",
                    "title",
                    "year",
                    "itemtype",
                    "is_oa",
                    "is_in_pure",
                    "has_pure_oai_match",
                    "openaccess",
                    "date",
                ],
                name="PureOpenAle_openale_0d2bf0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["openalex_url", "homepage_url", "display_name"],
                name="PureOpenAle_openale_52b0b8_idx",
            ),
        ),
        migrations.DeleteModel(
            name="PureAuthor",
        ),
    ]
