# Generated by Django 5.0.2 on 2024-02-29 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0024_remove_pureauthor_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pureentry",
            name="journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pure_entries",
                to="PureOpenAlex.journal",
            ),
        ),
        migrations.AddField(
            model_name="pureentry",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
