# Generated by Django 5.0.2 on 2024-03-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "PureOpenAlex",
            "0026_alter_location_options_alter_pureentry_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotPureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pureid", models.IntegerField()),
                ("title", models.CharField(max_length=512)),
                ("all_authors", models.JSONField()),
                ("orgs", models.JSONField()),
                ("doi", models.CharField(max_length=256)),
                ("other_links", models.URLField(max_length=256)),
                (
                    "apc_paid_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("file_names", models.JSONField()),
                ("article_number", models.CharField(max_length=256)),
                ("item_type", models.CharField(max_length=256)),
                ("year", models.IntegerField()),
                ("open_access", models.CharField(max_length=256)),
                ("keywords", models.JSONField()),
                ("ut_keyword", models.CharField(max_length=256)),
                ("import_source", models.CharField(max_length=256)),
                ("journal_title", models.CharField(max_length=512)),
                ("issn", models.CharField(max_length=256)),
                ("is_doaj", models.BooleanField()),
                ("publisher_journal", models.CharField(max_length=512)),
                ("ut_authors", models.JSONField()),
                ("date_earliest_published", models.DateField(null=True)),
                ("date_published", models.DateField(null=True)),
                ("date_eprint_first_online", models.DateField(null=True)),
                ("pure_entry_created", models.DateField()),
                ("pure_entry_last_modified", models.DateField()),
                ("pagescount", models.IntegerField()),
                ("pages", models.CharField(max_length=256)),
                ("event", models.CharField(max_length=256)),
                ("publisher_other", models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name="pureentry",
            name="pilot_pure_data",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pure_entries",
                to="PureOpenAlex.pilotpuredata",
            ),
        ),
    ]
