# Generated by Django 5.0.2 on 2024-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0027_pilotpuredata_pureentry_pilot_pure_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilotpuredata",
            name="apc_paid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="article_number",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="event",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="import_source",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="journal_title",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="open_access",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="other_links",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="pages",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="pagescount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="publisher_journal",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="publisher_other",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="ut_keyword",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
