# Generated by Django 5.0.2 on 2024-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0028_alter_pilotpuredata_apc_paid_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilotpuredata",
            name="doi",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="event",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="other_links",
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="ut_keyword",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
