# Generated by Django 5.0.2 on 2024-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "PureOpenAlex",
            "0029_alter_pilotpuredata_doi_alter_pilotpuredata_event_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["-is_ut", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["country_code", "name"]},
        ),
        migrations.AlterModelOptions(
            name="paper",
            options={"ordering": ["-year", "doi"]},
        ),
        migrations.AlterModelOptions(
            name="pilotpuredata",
            options={"ordering": ["-year", "pureid"]},
        ),
        migrations.AlterModelOptions(
            name="pureentry",
            options={"ordering": ["-year", "doi"]},
        ),
        migrations.AddIndex(
            model_name="pilotpuredata",
            index=models.Index(
                fields=["pureid", "title", "doi", "year"],
                name="PureOpenAle_pureid_276976_idx",
            ),
        ),
    ]
