# Generated by Django 5.0.2 on 2024-03-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0031_alter_journal_dealdata_alter_location_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pureentry",
            name="pilot_pure_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pure_entries",
                to="PureOpenAlex.pilotpuredata",
            ),
        ),
    ]
