# Generated by Django 5.0.2 on 2024-03-11 13:38

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0032_alter_pureentry_pilot_pure_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viewpaper",
            options={"ordering": ["-user"]},
        ),
        migrations.CreateModel(
            name="DBUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("details", models.JSONField()),
                ("update_source", models.CharField(blank=True, max_length=256)),
                ("update_type", models.CharField(blank=True, max_length=256)),
                (
                    "updated_papers",
                    models.ManyToManyField(
                        related_name="db_updates", to="PureOpenAlex.paper"
                    ),
                ),
                (
                    "updated_pure_entries",
                    models.ManyToManyField(
                        related_name="db_updates", to="PureOpenAlex.pureentry"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["update_source", "update_type"],
                        name="PureOpenAle_update__b08419_idx",
                    )
                ],
            },
        ),
    ]
