# Generated by Django 5.0.2 on 2024-03-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0034_remove_dbupdate_updated_papers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="title",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="pilotpuredata",
            name="title",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="pureentry",
            name="title",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
