# Generated by Django 5.0.2 on 2024-03-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0036_alter_paper_pdf_link_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utdata",
            name="avatar_path",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
