# Generated by Django 5.0.2 on 2024-03-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0037_utdata_avatar_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorship",
            name="ut_author_year_match",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="has_any_ut_author_year_match",
            field=models.BooleanField(null=True),
        ),
    ]
