# Generated by Django 5.0.2 on 2024-03-18 23:21

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0038_authorship_ut_author_year_match_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MUSPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=256)),
                ("openalex_url", models.CharField(blank=True, max_length=256)),
                ("url", models.CharField(blank=True, max_length=256)),
                ("is_oa", models.BooleanField(null=True)),
                ("from_pure", models.BooleanField(null=True)),
                ("year", models.CharField(blank=True, max_length=256)),
                ("filename", models.CharField(blank=True, max_length=256)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pdfs",
                        to="PureOpenAlex.location",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pdfs",
                        to="PureOpenAlex.paper",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["paper", "location"],
                        name="PureOpenAle_paper_i_0f069b_idx",
                    )
                ],
            },
        ),
    ]
