# Generated by Django 5.0.2 on 2024-03-30 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0039_muspdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pureentry",
            name="pilot_pure_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pure_entries",
                to="PureOpenAlex.pilotpuredata",
            ),
        ),
    ]
