# Generated by Django 5.0.2 on 2024-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0040_alter_pureentry_pilot_pure_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="date",
            field=models.DateField(),
        ),
    ]
