# Generated by Django 5.0.2 on 2024-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0041_alter_paper_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="calc_taverne_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
