# Generated by Django 5.0.2 on 2024-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PureOpenAlex", "0044_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="pureentry",
            name="checked_for_match",
            field=models.BooleanField(default=False),
        ),
    ]
