version: "3.1"

services:

  db:
    restart: always
    image: postgres
    container_name: postgres 
    hostname: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=database
      - POSTGRES_DB=refactor_testing
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin 
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: samopsa@gmail.com
        PGADMIN_DEFAULT_PASSWORD: bazending
      restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /docker/appdata/redis/data:/root/redis
      - /docker/appdata/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=bazending
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
       - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: smops
      MONGO_INITDB_ROOT_PASSWORD: bazending
    volumes:
     - mongodbdata:/data/db:rw

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8050:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: smops
      ME_CONFIG_MONGODB_ADMINPASSWORD: bazending
      ME_CONFIG_MONGODB_URL: mongodb://smops:bazending@mongo:27017/
    volumes:
      - /docker/appdata/mongo-express/db:/data/db:rw
      

volumes:
  postgres_data:
  mongodbdata: