from django.db import models
from django_extensions.db.models import TimeStampedModel

class Source(TimeStampedModel, models.Model):
    host_journal = models.ForeignKey('Publisher', on_delete=models.DO_NOTHING, related_name="sources", null=True)
    host_org = models.ForeignKey('Organization', on_delete=models.DO_NOTHING, related_name="sources", null=True)
    
    abbreviated_title = models.CharField(null=True)
    alternate_titles = models.JSONField(null=True)
    cited_by_count = models.IntegerField()
    country_code = models.CharField(null=True)
    counts_by_year = models.JSONField(null=True)
    openalex_created_date = models.DateField()
    openalex_updated_date = models.DateField()
    openalex_id = models.CharField()
    is_in_doaj = models.BooleanField()
    is_oa = models.BooleanField()
    name = models.CharField()
    homepage_url = models.URLField(null=True)
    host_org_name = models.CharField(null=True)
    source_type = models.CharField(null=True)
    fatcat_id = models.CharField(null=True)
    issns = models.JSONField(null=True)
    issn_l = models.CharField(null=True)
    mag = models.CharField(null=True)
    wikidata = models.CharField(null=True)
    societies = models.JSONField(null=True)
    two_year_mean_citedness = models.FloatField(null=True)
    h_index = models.IntegerField(null=True)
    i10_index = models.IntegerField(null=True)
    works_api_url = models.URLField()
    works_count = models.IntegerField()

class DealData(TimeStampedModel, models.Model):
    openalex_source = models.ForeignKey('Source', on_delete=models.CASCADE, related_name="deals")
    deal_status = models.CharField()
    oa_type = models.CharField()
    issns = models.JSONField(null=True)
    journal_browser_url = models.URLField()
    keywords = models.JSONField(null=True)
    journal_publisher = models.CharField()
    journal_title = models.CharField()

class Publisher(TimeStampedModel, models.Model):
    parent_publisher = models.ForeignKey('Publisher', on_delete=models.DO_NOTHING, related_name="children", null=True)

    name = models.CharField()
    alternate_titles = models.JSONField(null=True)
    cited_by_count = models.IntegerField()
    country_codes = models.JSONField(null=True)
    counts_by_year = models.JSONField(null=True)
    openalex_created_date = models.DateField()
    openalex_updated_date = models.DateField()
    openalex_id = models.CharField()
    ror = models.CharField()
    wikidata = models.CharField()
    image_thumbnail_url = models.URLField()
    image_url = models.URLField()
    roles = models.JSONField(null=True)
    sources_api_url = models.URLField()
    two_year_mean_citedness = models.FloatField(null=True)
    h_index = models.IntegerField(null=True)
    i10_index = models.IntegerField(null=True)
    works_count = models.IntegerField()

class Location(TimeStampedModel, models.Model):
    work = models.ForeignKey('Work', on_delete=models.CASCADE, related_name="locations")
    source = models.ForeignKey('Source', on_delete=models.DO_NOTHING, related_name="works")

    is_oa = models.BooleanField()
    is_primary = models.BooleanField()
    is_best_oa = models.BooleanField()
    is_accepted = models.BooleanField()
    is_published = models.BooleanField()
    landing_page_url = models.URLField(null=True)
    pdf_url = models.URLField(null=True)
    license = models.CharField(null=True)
    version = models.CharField(null=True)
