"""
Django settings for mus project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from loguru import logger
from pyzotero import zotero

dotenv_path = 'secrets.env'
load_dotenv(dotenv_path)

MONGOURL = str(os.getenv('MONGOURL'))
APIEMAIL = str(os.getenv('APIEMAIL'))
OPENAIRETOKEN = str(os.getenv('OPENAIRETOKEN'))
ZOTERO_PUBLIC = str(os.getenv('ZOTERO_PUBLIC'))
ZOTERO_PRIVATE = str(os.getenv('ZOTERO_PRIVATE'))
ZOTERO = zotero.Zotero(ZOTERO_PUBLIC, 'user', ZOTERO_PRIVATE)
SCRAPEOPSKEY = str(os.getenv('SCRAPEOPSKEY'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = str(os.getenv('DJANGOSECRETKEY'))
ACCOUNT_ADAPTER = "accounts.adapter.NoNewUsersAccountAdapter"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
LOGLEVEL = "DEBUG"
LOGFMT = "{time:[%m %d] %H:%M:%S} | {name}>{function}() [{level}] |> {message}"
logger.remove()
logger.add('log_mus.log', format=LOGFMT, level=LOGLEVEL)

ALLOWED_HOSTS = [
    "openalex.samuelmok.cc",
    "127.0.0.1",
    ".localhost",
    "*.samuelmok.cc",
    "[::1]" "*",
    'mus.samuelmok.cc',
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    "https://openalex.samuelmok.cc",
    "https://*.samuelmok.cc",
    "https://127.0.0.1",
    "https://openalex.samuelmok.cc/api",
    'https://openalex.samuelmok.cc/api/docs',
    'https://mus.samuelmok.cc',


]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "PureOpenAlex.apps.PureopenalexConfig",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "accounts",
    'mus_backend',
    'corsheaders',
    "data_browser",
    "django_extensions",
    "ajax_datatable",
    "slippers",
   # 'debug_toolbar',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    #"debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "https://openalex.samuelmok.cc",
    "https://samuelmok.cc",
    "https://127.0.0.1:9000"
    "https://127.0.0.1:3000",
    'https://mus.samuelmok.cc',
]
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = "mus.urls"
CORS_ALLOW_CREDENTIALS = True


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "builtins": ["slippers.templatetags.slippers"],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mus.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": str(os.getenv('POSTGRESDB')),
        "USER": str(os.getenv('POSTGRESUSER')),
        "HOST": str(os.getenv('POSTGRESHOST')),
        "PORT": str(os.getenv('POSTGRESPORT')),
        "PASSWORD": str(os.getenv('POSTGRESPWD')),
    }
}
print(DATABASES)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": str(os.getenv('REDISHOST')),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "default",
    },
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = str(os.getenv('STATICROOT'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

ACCOUNT_EMAIL_VERIFICATION = "none"
EMAIL_BACKEND = "django.core.mail.backends.dummy.EmailBackend"

INTERNAL_IPS = [
    "127.0.0.1",
]

GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

CACHE_TTL = 60 * 5

