# Generated by Django 5.0.6 on 2024-05-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="h_index",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="i10_index",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="impact_factor",
            field=models.FloatField(null=True),
        ),
    ]
