# Generated by Django 5.0.6 on 2024-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "xclass_refactor",
            "0002_alter_publisher_h_index_alter_publisher_i10_index_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="avatar_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="openalex_id",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="orcid",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="profile_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="research_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="works_api_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="dealdata",
            name="jb_url",
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="dealdata",
            name="openalex_id",
            field=models.URLField(max_length=20000, unique=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="doi",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="homepage_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="image_thumbnail_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="image_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="openalex_id",
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="funder",
            name="ror",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="wikidata",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="grant",
            name="openalex_id",
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="location",
            name="landing_page_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="pdf_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="image_thumbnail_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="image_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="openalex_id",
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="organization",
            name="wikidata",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="wikipedia",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="image_thumbnail_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="image_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="openalex_id",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="sources_api_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="wikidata",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="fatcat",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="homepage_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="openalex_id",
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="source",
            name="wikidata",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="works_api_url",
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="topic",
            name="openalex_id",
            field=models.URLField(max_length=20000, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="wikipedia",
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="work",
            name="cited_by_api_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="ngrams_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="oa_url",
            field=models.URLField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="openalex_id",
            field=models.URLField(max_length=20000, null=True),
        ),
    ]
