# Generated by Django 5.0.6 on 2024-05-26 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "xclass_refactor",
            "0003_alter_author_avatar_url_alter_author_openalex_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funder",
            name="as_orgs",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="types",
        ),
    ]
