# Generated by Django 5.0.6 on 2024-05-26 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0004_remove_funder_as_orgs_remove_organization_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to="xclass_refactor.source",
            ),
        ),
    ]
