# Generated by Django 5.0.6 on 2024-05-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0004_alter_topic_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="openalex_created_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="country_code",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="openalex_created_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="organization",
            name="openalex_created_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="openalex_created_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="openalex_created_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="work",
            name="openalex_created_date",
            field=models.DateField(null=True),
        ),
    ]
