# Generated by Django 5.0.6 on 2024-05-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0005_alter_work_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="primary_topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_works",
                to="xclass_refactor.topic",
            ),
        ),
    ]
