# Generated by Django 5.0.6 on 2024-05-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0005_alter_author_openalex_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealdata",
            name="jb_url",
            field=models.URLField(),
        ),
    ]
