# Generated by Django 5.0.6 on 2024-05-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0006_alter_work_primary_topic"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="grant",
            name="xclass_refa_openale_e3965f_idx",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="openalex_id",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="works",
        ),
        migrations.AddField(
            model_name="authorship",
            name="affiliations",
            field=models.ManyToManyField(
                related_name="authorships", to="xclass_refactor.organization"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="work",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="xclass_refactor.work",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="grant",
            name="funder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="xclass_refactor.funder",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="funder_name",
            field=models.CharField(null=True),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["funder_name"], name="xclass_refa_funder__03e554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(fields=["work"], name="xclass_refa_work_id_8f9975_idx"),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["funder"], name="xclass_refa_funder__38a3d0_idx"
            ),
        ),
    ]
