# Generated by Django 5.0.6 on 2024-05-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0006_alter_dealdata_jb_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealdata",
            name="journal_title",
            field=models.CharField(),
        ),
    ]
