# Generated by Django 5.0.6 on 2024-05-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xclass_refactor", "0008_alter_location_source"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["pure_uuid"], name="xclass_refa_pure_uu_9b39d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["pure_id"], name="xclass_refa_pure_id_84de30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["orcid"], name="xclass_refa_orcid_eba701_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["scopus"], name="xclass_refa_scopus_f58df1_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["isni"], name="xclass_refa_isni_3ee256_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["email"], name="xclass_refa_email_5fa3d4_idx"),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_id"], name="xclass_refa_openale_784807_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_display_name"], name="xclass_refa_openale_b569f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_issn"], name="xclass_refa_openale_b52132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_issn_l"], name="xclass_refa_openale_61da34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["openalex_type"], name="xclass_refa_openale_64617a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["journal_title"], name="xclass_refa_journal_56407f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["publisher_name"], name="xclass_refa_publish_e6f226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(fields=["jb_url"], name="xclass_refa_jb_url_345b98_idx"),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(fields=["issns"], name="xclass_refa_issns_6c86e3_idx"),
        ),
        migrations.AddIndex(
            model_name="dealdata",
            index=models.Index(
                fields=["dealtype"], name="xclass_refa_dealtyp_4276ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["source", "source_type"], name="xclass_refa_source__a35f79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["landing_page_url"], name="xclass_refa_landing_b24248_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["pdf_url"], name="xclass_refa_pdf_url_cd4ff8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["license"], name="xclass_refa_license_f08e46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["license_id"], name="xclass_refa_license_94151a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_best_oa"], name="xclass_refa_is_best_e431ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_accepted"], name="xclass_refa_is_acce_9a21d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_published"], name="xclass_refa_is_publ_403c7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_primary"], name="xclass_refa_is_prim_3f6f40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["openalex_id"], name="xclass_refa_openale_7dd5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(fields=["ror"], name="xclass_refa_ror_22a13c_idx"),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["wikidata"], name="xclass_refa_wikidat_f78d8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["image_url"], name="xclass_refa_image_u_7708a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(
                fields=["image_thumbnail_url"], name="xclass_refa_image_t_d5f668_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["openalex_id"], name="xclass_refa_openale_ba05d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["issn_l"], name="xclass_refa_issn_l_b9e58e_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["issn"], name="xclass_refa_issn_aaf3c9_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["wikidata"], name="xclass_refa_wikidat_935d42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["source_type"], name="xclass_refa_source__459428_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["homepage_url"], name="xclass_refa_homepag_e76475_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["is_in_doaj"], name="xclass_refa_is_in_d_d4846c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["is_oa"], name="xclass_refa_is_oa_e4629d_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["country_code"], name="xclass_refa_country_228c5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["pmid"], name="xclass_refa_pmid_3aac23_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["pmcid"], name="xclass_refa_pmcid_a4b4b7_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["isbn"], name="xclass_refa_isbn_e24bf6_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["mag"], name="xclass_refa_mag_a7b09a_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["is_also_green"], name="xclass_refa_is_also_fa0ab8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["is_oa"], name="xclass_refa_is_oa_4f10f6_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["type_crossref"], name="xclass_refa_type_cr_d3f366_idx"
            ),
        ),
    ]
